# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Ellen

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Fabulous Website Magic

description: Stylish Jekyll Theme
author:
  name: Ellen
  email: eclinester@gmail.com
  github: efcline
  twitter: ellen_cline
  pinterest:
  linkedin:
  bio: Still learning.
  email_md5: 6a67e994c474765f30dd7649561a8a09

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate